version: '3.8'
services:
  app:
    container_name: spring-boot-docker
    image: spring-boot-docker
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    expose:
      - "5434"
    ports:
      - "5434:5434"
    environment:
      - POSTGRES_DB=postgresdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
