apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-kubernetes
spec:
  selector:
    matchLabels:
      app: spring-boot-kubernetes-postgres
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-boot-kubernetes-postgres
    spec:
      containers:
        - name: spring-boot-kubernetes
          image: spring-boot-k8s:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD

---

apiVersion: v1
kind: Service
metadata:
  name: spring-boot-kubernetes-svc
spec:
  selector:
    app: spring-boot-kubernetes-postgres
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort